sudo: required
services:
  - docker

before_install:
  - docker build -t ztaylor510/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true ztaylor510/docker-react yarn test --coverage